[
  {
    "cmd": [],
    "name": "RECIPE CRASH (Uncaught exception)",
    "~followup_annotations": [
      "@@@STEP_EXCEPTION@@@",
      "The recipe has crashed at point 'Uncaught exception'!",
      "",
      "Traceback (most recent call last):",
      "  File \"RECIPE_REPO[flutter]/recipes/devicelab/devicelab_drone.py\", line 24, in RunSteps",
      "    raise ValueError('A task_name property is required')",
      "ValueError: A task_name property is required"
    ]
  },
  {
    "failure": {
      "humanReason": "Uncaught Exception: ValueError('A task_name property is required',)"
    },
    "name": "$result"
  }
]