[
  {
    "cmd": [
      "vpython3",
      "-u",
      "RECIPE_MODULE[recipe_engine::file]/resources/fileutil.py",
      "--json-output",
      "/path/to/tmp/json",
      "listdir",
      "[START_DIR]/out/android_profile/zip_archives/download.flutter.io",
      "--recursive"
    ],
    "infra_step": true,
    "luci_context": {
      "realm": {
        "name": "flutter:try"
      },
      "resultdb": {
        "current_invocation": {
          "name": "invocations/build:8945511751514863184",
          "update_token": "token"
        },
        "hostname": "rdbhost"
      }
    },
    "name": "Expand directory",
    "~followup_annotations": [
      "@@@STEP_LOG_LINE@listdir@[START_DIR]/out/android_profile/zip_archives/download.flutter.io/io/flutter/x86_debug/1.0.0-0005149dca9b248663adcde4bdd7c6c915a76584/x86_debug-1.0.0-0005149dca9b248663adcde4bdd7c6c915a76584.jar@@@",
      "@@@STEP_LOG_LINE@listdir@[START_DIR]/out/android_profile/zip_archives/download.flutter.io/io/flutter/x86_debug/1.0.0-0005149dca9b248663adcde4bdd7c6c915a76584/x86_debug-1.0.0-0005149dca9b248663adcde4bdd7c6c915a76584.pom@@@",
      "@@@STEP_LOG_END@listdir@@@"
    ]
  },
  {
    "cmd": [
      "git",
      "rev-parse",
      "HEAD"
    ],
    "cwd": "[START_DIR]/flutter",
    "infra_step": true,
    "luci_context": {
      "realm": {
        "name": "flutter:try"
      },
      "resultdb": {
        "current_invocation": {
          "name": "invocations/build:8945511751514863184",
          "update_token": "token"
        },
        "hostname": "rdbhost"
      }
    },
    "name": "git rev-parse"
  },
  {
    "cmd": [],
    "name": "RECIPE CRASH (Uncaught exception)",
    "~followup_annotations": [
      "@@@STEP_EXCEPTION@@@",
      "The recipe has crashed at point 'Uncaught exception'!",
      "",
      "Traceback (most recent call last):",
      "  File \"RECIPE_REPO[flutter]/recipe_modules/archives/examples/full.py\", line 25, in RunSteps",
      "    assert False, 'Unexpected file generated %s' % result.remote",
      "AssertionError('Unexpected file generated gs://flutter_archives_v2/flutter_infra_release/flutter/12345abcde12345abcde12345abcde12345abcde/android-arm-profile/artifacts.zip')"
    ]
  },
  {
    "failure": {
      "humanReason": "Uncaught Exception: AssertionError('Unexpected file generated gs://flutter_archives_v2/flutter_infra_release/flutter/12345abcde12345abcde12345abcde12345abcde/android-arm-profile/artifacts.zip')"
    },
    "name": "$result"
  }
]