[
  {
    "cmd": [],
    "name": "get buildbucket id"
  },
  {
    "cmd": [],
    "name": "RECIPE CRASH (Uncaught exception)",
    "~followup_annotations": [
      "@@@STEP_EXCEPTION@@@",
      "The recipe has crashed at point 'Uncaught exception'!",
      "",
      "Traceback (most recent call last):",
      "  File \"RECIPE_REPO[flutter]/recipe_modules/monorepo/tests/test_monorepo.py\", line 17, in RunSteps",
      "    try_build_identifier = api.monorepo.try_build_identifier",
      "  File \"RECIPE_REPO[flutter]/recipe_modules/monorepo/api.py\", line 55, in try_build_identifier",
      "    self.m.step.empty(",
      "  File \"RECIPE_REPO[recipe_engine]/recipe_modules/step/api.py\", in empty",
      "    ret.presentation.status = status",
      "  File \"RECIPE_REPO[recipe_engine]/recipe_engine/engine_types.py\", in status",
      "    assert val in self.STATUSES",
      "AssertionError()"
    ]
  },
  {
    "failure": {
      "humanReason": "Uncaught Exception: AssertionError()"
    },
    "name": "$result"
  }
]