[
  {
    "cmd": [],
    "name": "validate luci builder json schemas",
    "~followup_annotations": [
      "@@@STEP_EXCEPTION@@@"
    ]
  },
  {
    "cmd": [
      "vpython",
      "-u",
      "RECIPE_MODULE[recipe_engine::file]/resources/fileutil.py",
      "--json-output",
      "/path/to/tmp/json",
      "copy",
      "[CACHE]/dev/try_builders.json",
      "/path/to/tmp/"
    ],
    "infra_step": true,
    "name": "validate luci builder json schemas.validate try json format",
    "~followup_annotations": [
      "@@@STEP_NEST_LEVEL@1@@@",
      "@@@STEP_LOG_LINE@try_builders.json@{@@@",
      "@@@STEP_LOG_LINE@try_builders.json@  \"builders\": [@@@",
      "@@@STEP_LOG_LINE@try_builders.json@    {@@@",
      "@@@STEP_LOG_LINE@try_builders.json@      \"repo\": \"abc\"@@@",
      "@@@STEP_LOG_LINE@try_builders.json@    }@@@",
      "@@@STEP_LOG_LINE@try_builders.json@  ]@@@",
      "@@@STEP_LOG_LINE@try_builders.json@}@@@",
      "@@@STEP_LOG_END@try_builders.json@@@"
    ]
  },
  {
    "cmd": [],
    "name": "validate luci builder json schemas.validate try builders",
    "~followup_annotations": [
      "@@@STEP_NEST_LEVEL@1@@@",
      "@@@STEP_EXCEPTION@@@"
    ]
  },
  {
    "cmd": [],
    "name": "RECIPE CRASH (Uncaught exception)",
    "~followup_annotations": [
      "@@@STEP_EXCEPTION@@@",
      "The recipe has crashed at point 'Uncaught exception'!",
      "",
      "Traceback (most recent call last):",
      "  File \"RECIPE_REPO[flutter]/recipe_modules/json_util/examples/validate_json.py\", line 14, in RunSteps",
      "    api.json_util.validate_json(api.path['cache'])",
      "  File \"RECIPE_REPO[flutter]/recipe_modules/json_util/api.py\", line 23, in validate_json",
      "    self.validate_builder_schema('try', try_json_data)",
      "  File \"RECIPE_REPO[flutter]/recipe_modules/json_util/api.py\", line 85, in validate_builder_schema",
      "    'Missing key: name in builder: %s' % self.m.json.dumps(builder)",
      "ValueError: Missing key: name in builder: {\"repo\": \"abc\"}"
    ]
  },
  {
    "failure": {
      "humanReason": "Uncaught Exception: ValueError('Missing key: name in builder: {\"repo\": \"abc\"}',)"
    },
    "name": "$result"
  }
]